version: 2
jobs:
  API_Document:
    working_directory: ~/scripts
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Installing node dependencies
          command: |
#            npm install protagonist
            npm install aglio

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules


      - run:
          name: Blueprint validator
          command: node test.js

      - run:
           command: |
             mkdir /home/circleci/scripts/apidoc;
             node_modules/.bin/aglio -i apiary.apib --theme-template triple -o /home/circleci/scripts/apidoc/apidocument.html

      - store_artifacts:
          path: /home/circleci/scriptsapidoc/



workflows:
  version: 2
  Build_Test:
    jobs:
      - API_Document
