## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
## Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run

version: 2
jobs:
  build:
    working_directory: ~/scripts
    docker:
      - image: tomjowitt/docker-node
    steps:
      - checkout
      - restore_cache:
          key: bolapi-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}

      - run:
          name: Install node dependencies
          command: |
            npm install protagonist

      - save_cache:
          key: bolapi-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          command: |
            node test.js
workflows:
  version: 2
  Build_Test:
    jobs:
      - build

